"""create users table

Revision ID: 352ab7f7207a
Revises:
Create Date: 2026-05-01 16:10:31.805544

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "352ab7f7207a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
